-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	HoudiniEngineBadge = "rbxassetid://15429695742",
	Navbar = {
		Assets = function(dpiScale)
			if dpiScale >= 2 then
				return {
					Image = "rbxassetid://15431563615",
					ImageRectOffset = Vector2.new(0, 0),
					ImageRectSize = Vector2.new(36, 30),
				}
			else
				return {
					Image = "rbxassetid://15431563463",
					ImageRectOffset = Vector2.new(0, 0),
					ImageRectSize = Vector2.new(18, 15),
				}
			end
		end,
		Properties = function(dpiScale)
			if dpiScale >= 2 then
				return {
					Image = "rbxassetid://15431563615",
					ImageRectOffset = Vector2.new(37, 0),
					ImageRectSize = Vector2.new(32, 32),
				}
			else
				return {
					Image = "rbxassetid://15431563463",
					ImageRectOffset = Vector2.new(19, 0),
					ImageRectSize = Vector2.new(16, 16),
				}
			end
		end,
		Settings = function(dpiScale)
			if dpiScale >= 2 then
				return {
					Image = "rbxassetid://15431563615",
					ImageRectOffset = Vector2.new(0, 31),
					ImageRectSize = Vector2.new(31, 32),
				}
			else
				return {
					Image = "rbxassetid://15431563463",
					ImageRectOffset = Vector2.new(0, 16),
					ImageRectSize = Vector2.new(16, 16),
				}
			end
		end,
	},
}
