-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	ConnectScreen = {
		HapiLogo_Dark = function(dpiScale)
			if dpiScale >= 2 then
				return {
					Image = "rbxassetid://15439199312",
					ImageRectOffset = Vector2.new(0, 54),
					ImageRectSize = Vector2.new(310, 52),
				}
			else
				return {
					Image = "rbxassetid://15439199176",
					ImageRectOffset = Vector2.new(0, 28),
					ImageRectSize = Vector2.new(155, 26),
				}
			end
		end,
		HapiLogo_Light = function(dpiScale)
			if dpiScale >= 2 then
				return {
					Image = "rbxassetid://15439199312",
					ImageRectOffset = Vector2.new(0, 0),
					ImageRectSize = Vector2.new(310, 53),
				}
			else
				return {
					Image = "rbxassetid://15439199176",
					ImageRectOffset = Vector2.new(0, 0),
					ImageRectSize = Vector2.new(155, 27),
				}
			end
		end,
	},
	HoudiniEngineBadge = "rbxassetid://15429695742",
	Misc = {
		SearchIcon = function(dpiScale)
			if dpiScale >= 2 then
				return {
					Image = "rbxassetid://15439199312",
					ImageRectOffset = Vector2.new(348, 0),
					ImageRectSize = Vector2.new(24, 24),
				}
			else
				return {
					Image = "rbxassetid://15439199176",
					ImageRectOffset = Vector2.new(175, 0),
					ImageRectSize = Vector2.new(12, 12),
				}
			end
		end,
	},
	Navbar = {
		Assets = function(dpiScale)
			if dpiScale >= 2 then
				return {
					Image = "rbxassetid://15439199312",
					ImageRectOffset = Vector2.new(311, 0),
					ImageRectSize = Vector2.new(36, 30),
				}
			else
				return {
					Image = "rbxassetid://15439199176",
					ImageRectOffset = Vector2.new(156, 0),
					ImageRectSize = Vector2.new(18, 15),
				}
			end
		end,
		Properties = function(dpiScale)
			if dpiScale >= 2 then
				return {
					Image = "rbxassetid://15439199312",
					ImageRectOffset = Vector2.new(311, 54),
					ImageRectSize = Vector2.new(32, 32),
				}
			else
				return {
					Image = "rbxassetid://15439199176",
					ImageRectOffset = Vector2.new(156, 28),
					ImageRectSize = Vector2.new(16, 16),
				}
			end
		end,
		Settings = function(dpiScale)
			if dpiScale >= 2 then
				return {
					Image = "rbxassetid://15439199312",
					ImageRectOffset = Vector2.new(0, 107),
					ImageRectSize = Vector2.new(31, 32),
				}
			else
				return {
					Image = "rbxassetid://15439199176",
					ImageRectOffset = Vector2.new(0, 55),
					ImageRectSize = Vector2.new(16, 16),
				}
			end
		end,
	},
}