-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	AssetsScreen = {
		AssetIcon = function(dpiScale)
			if dpiScale >= 2 then
				return {
					Image = "rbxassetid://15451013147",
					ImageRectOffset = Vector2.new(344, 54),
					ImageRectSize = Vector2.new(28, 28),
				}
			else
				return {
					Image = "rbxassetid://15451013005",
					ImageRectOffset = Vector2.new(173, 28),
					ImageRectSize = Vector2.new(14, 14),
				}
			end
		end,
		Breadcrumbs = {
			CaretRight = function(dpiScale)
				if dpiScale >= 2 then
					return {
						Image = "rbxassetid://15451013147",
						ImageRectOffset = Vector2.new(0, 140),
						ImageRectSize = Vector2.new(8, 16),
					}
				else
					return {
						Image = "rbxassetid://15451013005",
						ImageRectOffset = Vector2.new(0, 72),
						ImageRectSize = Vector2.new(4, 8),
					}
				end
			end,
		},
		FolderIcon = function(dpiScale)
			if dpiScale >= 2 then
				return {
					Image = "rbxassetid://15451013147",
					ImageRectOffset = Vector2.new(348, 0),
					ImageRectSize = Vector2.new(32, 28),
				}
			else
				return {
					Image = "rbxassetid://15451013005",
					ImageRectOffset = Vector2.new(175, 0),
					ImageRectSize = Vector2.new(16, 14),
				}
			end
		end,
		SortAsc = function(dpiScale)
			if dpiScale >= 2 then
				return {
					Image = "rbxassetid://15451013147",
					ImageRectOffset = Vector2.new(311, 31),
					ImageRectSize = Vector2.new(21, 13),
				}
			else
				return {
					Image = "rbxassetid://15451013005",
					ImageRectOffset = Vector2.new(156, 16),
					ImageRectSize = Vector2.new(11, 7),
				}
			end
		end,
		SortDesc = function(dpiScale)
			if dpiScale >= 2 then
				return {
					Image = "rbxassetid://15451013147",
					ImageRectOffset = Vector2.new(32, 107),
					ImageRectSize = Vector2.new(21, 13),
				}
			else
				return {
					Image = "rbxassetid://15451013005",
					ImageRectOffset = Vector2.new(17, 55),
					ImageRectSize = Vector2.new(11, 7),
				}
			end
		end,
	},
	ConnectScreen = {
		HapiLogo_Dark = function(dpiScale)
			if dpiScale >= 2 then
				return {
					Image = "rbxassetid://15451013147",
					ImageRectOffset = Vector2.new(0, 54),
					ImageRectSize = Vector2.new(310, 52),
				}
			else
				return {
					Image = "rbxassetid://15451013005",
					ImageRectOffset = Vector2.new(0, 28),
					ImageRectSize = Vector2.new(155, 26),
				}
			end
		end,
		HapiLogo_Light = function(dpiScale)
			if dpiScale >= 2 then
				return {
					Image = "rbxassetid://15451013147",
					ImageRectOffset = Vector2.new(0, 0),
					ImageRectSize = Vector2.new(310, 53),
				}
			else
				return {
					Image = "rbxassetid://15451013005",
					ImageRectOffset = Vector2.new(0, 0),
					ImageRectSize = Vector2.new(155, 27),
				}
			end
		end,
	},
	EngineBadge_DarkTheme = "rbxassetid://15450131327",
	EngineBadge_LightTheme = "rbxassetid://15450139652",
	Misc = {
		SearchIcon = function(dpiScale)
			if dpiScale >= 2 then
				return {
					Image = "rbxassetid://15451013147",
					ImageRectOffset = Vector2.new(311, 87),
					ImageRectSize = Vector2.new(24, 24),
				}
			else
				return {
					Image = "rbxassetid://15451013005",
					ImageRectOffset = Vector2.new(156, 45),
					ImageRectSize = Vector2.new(12, 12),
				}
			end
		end,
	},
	Navbar = {
		Assets = function(dpiScale)
			if dpiScale >= 2 then
				return {
					Image = "rbxassetid://15451013147",
					ImageRectOffset = Vector2.new(311, 0),
					ImageRectSize = Vector2.new(36, 30),
				}
			else
				return {
					Image = "rbxassetid://15451013005",
					ImageRectOffset = Vector2.new(156, 0),
					ImageRectSize = Vector2.new(18, 15),
				}
			end
		end,
		Properties = function(dpiScale)
			if dpiScale >= 2 then
				return {
					Image = "rbxassetid://15451013147",
					ImageRectOffset = Vector2.new(311, 54),
					ImageRectSize = Vector2.new(32, 32),
				}
			else
				return {
					Image = "rbxassetid://15451013005",
					ImageRectOffset = Vector2.new(156, 28),
					ImageRectSize = Vector2.new(16, 16),
				}
			end
		end,
		Settings = function(dpiScale)
			if dpiScale >= 2 then
				return {
					Image = "rbxassetid://15451013147",
					ImageRectOffset = Vector2.new(0, 107),
					ImageRectSize = Vector2.new(31, 32),
				}
			else
				return {
					Image = "rbxassetid://15451013005",
					ImageRectOffset = Vector2.new(0, 55),
					ImageRectSize = Vector2.new(16, 16),
				}
			end
		end,
	},
}